# Load required packages
library(inlabru)
library(INLA)  # need testing version of inla
library(sf)
library(ggplot2)

data_path = here::here("R", "data")
point_transects <- readRDS(here::here(data_path, "samplers.RDS"))
study_area <- readRDS(here::here(data_path,"study_area.RDS"))
outer_boundary = st_buffer(study_area, dist = 10)

# meshbuilder()

## Generated by meshbuilder()

## Build boundary information:
## (fmesher supports SpatialPolygons, but this app is not (yet) intelligent enough for that.)
boundary <- list(
  fm_as_segm(study_area),
  fm_as_segm(outer_boundary)
)

## Build the mesh:
mesh <- fm_mesh_2d_inla(boundary=boundary,
                        max.edge=c(0.2, 4.1),
                        min.angle=c(27, 25),
                        max.n=c(48000, 16000), ## Safeguard against large meshes.
                        max.n.strict=c(128000, 128000), ## Don't build a huge mesh!
                        cutoff=0.076, ## Filter away adjacent points.
                        offset=c(0.1, 0.3)) ## Offset for extra boundaries, if needed.


# plot whole mesh
ggplot() +
  gg(mesh) +
  geom_sf(data = point_transects,
          colour = "red")

# zoom in a bit
ggplot() +
  gg(mesh) +
  xlim(c(250, 267)) +
  ylim(c(2183, 2210))

# save the mesh
saveRDS(object = mesh,
        file = here::here(data_path,"mesh.RDS"))
