# Load required packages
library(inlabru)
library(INLA) # need testing version of inla
library(sf)
library(ggplot2)

data_path <- here::here("R", "data")
point_transects <- readRDS(here::here(data_path, "samplers.RDS"))
study_area <- readRDS(here::here(data_path, "study_area.RDS"))
outer_boundary <- fm_nonconvex_hull(study_area, convex = 10)

# meshbuilder()

## Originally generated by meshbuilder(), then modified.

## Build boundary information:
boundary <- list(
  study_area,
  outer_boundary
)

## Build the mesh:
mesh_old <- fm_mesh_2d_inla(
  boundary = boundary,
  max.edge = c(0.2, 4.1),
  min.angle = c(27, 25),
  max.n = c(48000, 16000), ## Safeguard against large meshes.
  max.n.strict = c(128000, 128000), ## Don't build a huge mesh!
  cutoff = 0.076, ## Filter away adjacent points.
  offset = c(0.1, 0.3)
) ## Offset for extra boundaries, if needed.
mesh_hex <- fm_mesh_2d_inla(
  loc = fm_hexagon_lattice(study_area, edge_len = 0.15),
  boundary = boundary,
  max.edge = c(0.15 * 1.1, 4.1),
  min.angle = c(27, 25),
  max.n = c(48000, 16000), ## Safeguard against large meshes.
  max.n.strict = c(128000, 128000), ## Don't build a huge mesh!
  cutoff = 0.076, ## Filter away adjacent points.
  offset = c(0.1, 0.3)
) ## Offset for extra boundaries, if needed.

mesh <- mesh_hex


# plot whole mesh
ggplot() +
  gg(mesh) +
  geom_sf(
    data = point_transects,
    colour = "red"
  )

# zoom in a bit
ggplot() +
  gg(mesh) +
  geom_sf(
    data = point_transects,
    colour = "red"
  ) +
  coord_sf(
    xlim = c(254, 263),
    ylim = c(2188, 2202)
  )

# save the mesh
saveRDS(
  object = mesh,
  file = here::here(data_path, "mesh.RDS")
)
