# Load required packages
library(inlabru)
library(INLA)  # need testing version of inla

data_path = here::here("analyses", "data")
point_transects <- readRDS(here::here(data_path, "samplers_no_crs.RDS"))
study_area <- readRDS(here::here(data_path,"study_area_no_crs.RDS"))

# meshbuilder()

## Generated by meshbuilder()

## Build boundary information:
## (fmesher supports SpatialPolygons, but this app is not (yet) intelligent enough for that.)
boundary <- list(
  as.inla.mesh.segment(study_area),
  NULL)

## Build the mesh:
mesh <- inla.mesh.2d(boundary=boundary,
                     max.edge=c(280, 960),
                     min.angle=c(30, 21),
                     max.n=c(48000, 16000), ## Safeguard against large meshes.
                     max.n.strict=c(128000, 128000), ## Don't build a huge mesh!
                     cutoff=2, ## Filter away adjacent points.
                     offset=c(1100, 2000)) ## Offset for extra boundaries, if needed.

ggplot() + gg(mesh) + gg(point_transects, colour = "red")

# save the mesh
saveRDS(object = mesh, file = here::here(data_path,"mesh_no_crs.RDS"))
